CREATE TABLE post(
id SERIAL PRIMARY KEY, 
business_id INT REFERENCES business(id) ON DELETE CASCADE, 
images TEXT[], 
video VARCHAR(200), 
content text, 
status VARCHAR(100), 
type VARCHAR(100), 
dates TIMESTAMP[],
italic BOOLEAN,
bold BOOLEAN,
websites JSONB,
integrations TEXT[],
title VARCHAR(200),
created_at TIMESTAMP,
updated_at TIMESTAMP,
recurring_for VARCHAR(50),
recurring_on TEXT[],
recurring_every INT,
time VARCHAR(10),
u_start_date VARCHAR(20),
u_end_date VARCHAR(20),
u_selected_days TEXT[],
u_scheduled_date VARCHAR(20)
expire_at DATE
);