CREATE TABLE business( 
id SERIAL PRIMARY KEY, 
name VARCHAR(50), 
description VARCHAR(450),
email VARCHAR(50) UNIQUE,
phone_number VARCHAR(20) UNIQUE, 
category VARCHAR(30), 
state VARCHAR(30), 
web_site VARCHAR(100), 
street VARCHAR(50), 
city_zip VARCHAR(30), 
city1 VARCHAR(30), 
city2 VARCHAR(30), 
tags TEXT[], 
images TEXT[],
video VARCHAR(700),
logo VARCHAR(700),
likes INTEGER,
created_at DATE,
updated_at DATE,
expire_at DATE
);